import './globals.css'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { Toaster } from '@/components/ui/sonner'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const session = await auth()
  return (
   <SessionProvider session={session}>
     <html lang="en">
      <body>
        <Toaster />
        {children}
      </body>
    </html>
   </SessionProvider>
  )
}
